### ISSUE TITLE
feat: ed25519 verification support

### ISSUE THREAD

**Issue by iStrike7** [keep-starknet-strange/alexandria#100]
Implement ed25519 signature verification support
Preferably have it as a builtin for best performance
Preferably with batch verification for improved performance when verifying multiple signatures over the same message

Some prior requests for this that I came across in the ethereum space
https://github.com/starkware-libs/cairo-lang/issues/15
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-665.md

**Comment by edisontim** [comment]
I'll give this one a go

**Comment by edisontim** [comment]
Can we re-open this please? About to be merged

**Comment by edisontim** [comment]
Can be closed, PR was merged
