### ISSUE TITLE
bug: New interdependency between math and data_structures due to ed25519 feature

### ISSUE THREAD

**Issue by Bal7hazar** [keep-starknet-strange/alexandria#130]
# Bug Report

**Alexandria version:**

`main`

**Current behavior:**

Since the merge of ed25519 feature, there is a dependency between alexandria_math and alexandria_data_structures which force a user to add the alexandria_data_structures if he wants to only use alexandria_math.

**Expected behavior:**

I expected that each library would not be interdependent, but I could be wrong.

**Steps to reproduce:**

```bash
scarb add alexandria_math --git https://github.com/keep-starknet-strange/alexandria
scarb build
```

Generates the following error:

```bash
error: Identifier not found.
 --> ed25519.cairo:9:5
use alexandria_data_structures::array_ext::{ArrayTraitExt};
    ^************************^

error: Method `concat` not found on type "@core::array::Array::<core::integer::u8>". Did you import the correct trait and impl?
 --> ed25519.cairo:303:49
    let k: Array<u8> = sha512(r_string.snapshot.concat(pub_key.snapshot).concat(msg.snapshot));
                                                ^****^

error: Method `concat` not found on type "<missing>". Did you import the correct trait and impl?
 --> ed25519.cairo:303:74
    let k: Array<u8> = sha512(r_string.snapshot.concat(pub_key.snapshot).concat(msg.snapshot));
                                                                         ^****^
```

To solve this we could either not use alexandria_data_structures in alexandria_math, or merge both libraries.

Finally, this is a good opportunity to statuate on this situation and if possible add a test to prevent it in the future if we choose to avoid this situation.

**Related code:**

https://github.com/keep-starknet-strange/alexandria/blob/3fae57a07ba8904f8e8a4299448a5c2f443f8330/alexandria/math/src/ed25519.cairo#L9C1-L9C60

**Comment by edisontim** [comment]
I forgot to add alexandria_data_structures to the scarb.toml, but why not have interdependencies? The only issue I can see is recursive dependency, is there something else that might be annoying?
The reason I ask is because this happens as well in the package alexandria_encoding with base64, which imports rhs and lsh from alexandria_math.

**Comment by Bal7hazar** [comment]
> but why not have interdependencies?

I don't have strong opinion about interdependencies, I didn't notice any other so I was thinking that we have to avoid that. But as you mentioned base64 already did that so adding the dep in the scarb should be the right thing to do then.

Also, @LucasLvy if we create interdependencies what is the point to split libs, why not just to merge them all into an Alexandria lib? Is there any benefict to `use alexandria_math`  which uses `alexandria_data_structures` behind the scene vs just `use alexandria::math` with a single Scarb file at the top level?

**Comment by edisontim** [comment]
Also what I was thinking, maybe it would make sense to group everything into one package

**Comment by LucasLvy** [comment]
I'm not against inter deps but i fear that this will lead to having a cyclic dependency. I'd rather keep everything separated

**Comment by edisontim** [comment]
Ok, should we switch Alexandria to be only one package then? In the meantime I will remove any interdependencies

**Comment by Ginika-Chinonso** [comment]
> Also what I was thinking, maybe it would make sense to group everything into one package

I think this would be a good solution. People can then specify the one they want to use in their project.

**Comment by gaetbout** [comment]
This would lead to use it like this:
```rust
alexandria::math::pow;
alexandria::data_structure::ArrayTraitExt;
```
Is it better?

**Comment by Ginika-Chinonso** [comment]
> This would lead to use it like this:
> 
> ```rust
> alexandria::math::pow;
> alexandria::data_structure::ArrayTraitExt;
> ```
> 
> Is it better?

This would be much better

**Comment by LucasLvy** [comment]
I tend to agree that it'd be better. Do you have any argument against @gaetbout

**Comment by gaetbout** [comment]
None, I can work on this today ASAP and have it done by tomorrow.
I'm just concerned about breaking projects that might be using it already.

**Comment by edisontim** [comment]
I was already playing with it and almost have a working version, last step I need to figure out if it's an issue to run all tests with --starknet flag, as storage module needs it.

**Comment by gaetbout** [comment]
Wonder if it is somehow possible to make a release so that other project can somehow refer to that release in their scarb file.
I don't know this is possible

**Comment by edisontim** [comment]
It should be possible with this: https://docs.swmansion.com/scarb/docs/guides/dependencies#adding-a-dependency

**Comment by edisontim** [comment]
Here's what I propose for the merging of packages: https://github.com/keep-starknet-strange/alexandria/pull/136
