### ISSUE TITLE
bug: `sha256` not working in contract calls

### ISSUE THREAD

**Issue by delaaxe** [keep-starknet-strange/alexandria#142]
# Bug Report

**Alexandria version:** `2.0.0`

**Current behavior:**

When trying to use `sha256` inside a contract (after declared & deployed on local devnet):

```
     GatewayError: Error at pc=0:6831:
Error: Execution reached the end of the program.
Cairo traceback (most recent call last):
Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:5225)Unknown location (pc=0:4958)Unknown location (pc=0:6243)Unknown location (pc=0:1775)Unknown location (pc=0:4260)Unknown location (pc=0:5636)
```

**Steps to reproduce / related code:**

```rust
#[starknet::interface]
trait ITestDapp<TContractState> {
    fn get_hash(self: @TContractState) -> Array<u8>;
}

#[starknet::contract]
mod TestDapp {
    use array::ArrayTrait;
    use alexandria::math::sha256::sha256;

    #[storage]
    struct Storage {}

    #[external(v0)]
    impl TestDappImpl of super::ITestDapp<ContractState> {
        fn get_hash(self: @ContractState) -> Array<u8> {
            let mut arr = ArrayTrait::new();
            arr.append(1);
            arr.append(2);
            let client_data_hash = sha256(arr);
            client_data_hash
        }
    }
}

```

**Comment by gaetbout** [comment]
@neotheprogramist Any idea?

**Comment by neotheprogramist** [comment]
Hi, does other functions like base64, sha512 working?

**Comment by edisontim** [comment]
Isn't this because the computation takes too many steps?

**Comment by delaaxe** [comment]
@neotheprogramist base64 works, sha512 doesn't

@edisontim this is also what I guess the error means

**Comment by edisontim** [comment]
> I'm going to check that on my own, you have just created contract and called the sha256_view method right? When hashing only 2 bytes there should not be much to compute

There's quite a bit of calculation going on, it wouldn't surprise me that that's the case. For 0 to 55 bytes it takes pretty much the same number of steps by the way, increases by steps of 64 bytes

**Comment by delaaxe** [comment]
@neotheprogramist yes that's the case, if you comment the first call to `sha256_inner` the error goes, so there must be some extra overhead there

**Comment by neotheprogramist** [comment]
@gaetbout do you think we should increase limits though?

**Comment by gaetbout** [comment]
@neotheprogramist  which limits are you referring to?

**Comment by neotheprogramist** [comment]
@gaetbout I think that we should test with memory limits or gas limits on the virtual machine, but I'm not into that much so we may ask someone that specializes in that field.
End of the program indicates too low program memory allocated in my opinion

**Comment by neotheprogramist** [comment]
Ok, I'm going to take a look at that and try to optimise

**Comment by delaaxe** [comment]
update: `sha256` now works after upgrading to `cairo-lang==0.12` from 0.11, however `sha512` still fails with same error

**Comment by edisontim** [comment]
> cairo

Where do you change this value? I can have a look at this

**Comment by delaaxe** [comment]
@neotheprogramist any luck? on testnet it errors with `End of program was not reached`

https://goerli.voyager.online/contract/0x023653887a16cfd4616497b430ef16d7953ed963b2ed8879748209fa193efc13#readContract
