### ISSUE TITLE
feat: storage: `from_array` method for `List`

### ISSUE THREAD

**Issue by akirillo** [keep-starknet-strange/alexandria#158]
# Feature Request

**Describe the Feature Request**

I would love to have a simple method, `from_array`, on the `List` interface, which takes in a snapshot of an array and effectively calls `List.append` for every element in it, but only has to write the length to storage once (instead of on every append) since it is known ahead of time.

I've omitted the other feature request template sections since I think the request is pretty straightforward, but if you'd like me to explain in more detail, please let me know

**Comment by gaetbout** [comment]
GM,
Could you point me where is that length being increased multiple times?
