### ISSUE TITLE
feat: Accounts

### ISSUE THREAD

**Issue by 0xSidius** [keep-starknet-strange/alexandria#166]
OZ-like account contract template working with Cairo 2.1.0

**Comment by gaetbout** [comment]
As this is extremely sensitive code, I'd leave that responsibility to OZ

**Comment by 0xSidius** [comment]
> As this is extremely sensitive code, I'd leave that responsibility to OZ

which are completely asleep on cairo2 branch: https://github.com/OpenZeppelin/cairo-contracts/commits/cairo-2 0-substance maintenance commits for weeks.

not that i can blame them with cairo still changing as much as it does with every back to back release...
