### ISSUE TITLE
feat: Add method to drop duplicates in ArrayExtTrait

### ISSUE THREAD

**Issue by Bal7hazar** [keep-starknet-strange/alexandria#172]
# Feature Request

**Describe the Feature Request**

Droping duplicates would be interesting for many cases, especially after using a concat.

**Describe Preferred Solution**

Loop over the array, `pop_front` elements one by one and use `contains` to identifiy if the element already exists in the shortest array (input or ouput) then add the element in the ouput array.

**Describe Alternatives**

To discuss if needed.

**Related Code**

No related code.

**Additional Context**

Some references discussed in telegram:

- https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.unique
- https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.dedup

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes
- [ ] No

**Comment by akhercha** [comment]
Hey, can I take this one or is it outdated? Thanks!

**Comment by gaetbout** [comment]
@LucasLvy  this can be closed I think

**Comment by gaetbout** [comment]
@LucasLvy This can be closed
