### ISSUE TITLE
feat: Add clean method for list

### ISSUE THREAD

**Issue by Bal7hazar** [keep-starknet-strange/alexandria#177]
# Feature Request

**Describe the Feature Request**

To clean a List in a conctract state storage you can either remove each element of the list or just set the len to 0 (cairo-0 style).
Having a `clean`  or `reset` function attached to the ListTrait would help to democratize this option.

**Describe Preferred Solution**

Add a `clean` method to ListTrait.

**Describe Alternatives**

No alternatives.

**Related Code**

No related code.

**Additional Context**

No additional context.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by azurwastaken** [comment]
i'll take it if possible
