### ISSUE TITLE
bug: Compilation Error in scarb After Specifying a Rev from alexandria Repository

### ISSUE THREAD

**Issue by henryf10h** [keep-starknet-strange/alexandria#188]
Bug Report
Alexandria version:

Not specific to a version. Encountered while importing via scarb.toml.

Current behavior:

When trying to build using scarb, an error is encountered while updating the alexandria repository. The error message is:

```
error: failed to fetch into: /home/henryf10h/.cache/scarb/registry/git/db/alexandria-oen34onnk9gr0.git

Caused by:
    process did not exit successfully: exit status: 1
```

Expected behavior:

The scarb build command should fetch the required dependencies from the alexandria repository without any errors, especially if it was working correctly initially.

Steps to reproduce:

Add the alexandria repository to scarb.toml and list it under dependencies.
Specify a particular revision as seen in Satoru's repo:
{ git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "a3052ff" }
Run scarb build.
Observe the error.
Remove the rev = "a3052ff" specification and try building again.
Observe that the error persists.
Related code:

scarb.toml (snippet):

```
[dependencies]
alexandria = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "a3052ff" }
```
Other information:

The build process was functioning correctly prior to specifying the revision. Even after removing the revision specification, the error persists. Any assistance or insights into resolving this issue would be much appreciated.

Thanks beforehand.

**Comment by mkaput** [comment]
Hi! Scarb author here 😄 

There's no package named `alexandria` in this project. It used to be, but currently this is a workspace of many packages, for example `alexandria_ascii`.

---

Nonetheless, the behaviour you see is very off. Something is probably off between Scarb and your `git` installation. Can you please post what does the following command print? It should include `git` calls output in stderr:

```shell
scarb -vvv fetch
```

(If you're curious, there's even `scarb -vvvv fetch`, but I don't think I need that output)
