### ISSUE TITLE
feat: Add Wad_Ray_Math

### ISSUE THREAD

**Issue by FabienCoutant** [keep-starknet-strange/alexandria#211]
# Feature Request

**Describe the Feature Request**

  With more and more DeFi projects coming in starknet, the need of handling high decimals maths are required. I propose to start the implementation for the 27 decimals (following WadRayMath standard).

**Describe Preferred Solution**

Add under `Maths` or a specific folder: wad_ray_math.cairo (wad means for 18 decimals and ray for 27)

**Describe Alternatives**

**Related Code**

**Additional Context**

We could be inspired by [PRB-Math UD60x18](https://github.com/PaulRBerg/prb-math/tree/abdf0b28909fb2fb149c56cf841ef4d94f916e1e/test/unit/ud60x18)

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

Edit: rename UD27x18 by wad_ray_math to follow solidity feature

**Comment by LucasLvy** [comment]
I hereby approve the feature. You're now officially allowed to work on it
cc @gaetbout

**Comment by gaetbout** [comment]
@LucasLvy This can be closed
