### ISSUE TITLE
feat: Implement RLP Encoding and Decoding

### ISSUE THREAD

**Issue by Quentash** [keep-starknet-strange/alexandria#212]
# Feature Request

**Describe the Feature Request**

Recursive Length Prefix (RLP) serialization is used extensively in Ethereum's execution clients. RLP standardizes the transfer of data between nodes in a space-efficient format. The purpose of RLP is to encode arbitrarily nested arrays of binary data, and RLP is the primary encoding method used to serialize objects in Ethereum's execution layer.
Doc source : https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by enitrat** [comment]
@Quentash check https://github.com/kkrt-labs/kakarot-ssj/commit/7d150bff87ebf1e47b7733eaa854bfef12c36cd7
