### ISSUE TITLE
bug: Bubble sort infinite loops if 2 values are the same

### ISSUE THREAD

**Issue by 0xKawaka** [keep-starknet-strange/alexandria#217]
I think `if *array[idx1] < *array[idx2]` should be replace by if `*array[idx1] <= *array[idx2]` since it loops infinitely swapping the 2 elements  if they are the same values.
Maybe that's a feature if you want to sort an array and you know it doesn't contain duplicated values but I don't think it should be the default implementation.

**Comment by azurwastaken** [comment]
im on it

**Comment by azurwastaken** [comment]
This issues is resolved, can someone close it ?
