### ISSUE TITLE
why not derive(copy)  on List? 

### ISSUE THREAD

**Issue by JameWade** [keep-starknet-strange/alexandria#226]
when i defien a struct A with #[derive(copy)],and A has a List<B>,B is also a struct with #[derive(copy)].then A get a err
 Invalid copy trait implementation, Trait has no implementation in context: core::traits::Copy::<alexandria_storage::list::List::<petfight::structs::b::B>>.
then I add derive(copy)  on struct List,it worked.

**Comment by enitrat** [comment]
List should never be part of a struct - rather, it should only be used when interacting from / to storage. Otherwise, the internal storage addresses of elements in the struct will collide!!

**Comment by LucasLvy** [comment]
All struct fields are stored next to each other. Let's take this as example

```rs
struct Foo {
    bar: felt252,
    baz: u256
}
```

Let's take m as the cell number in your smart contract. m is computed as follow: `sn_keccak(VAR_NAME)`. For the `Foo` struct `m = 0x0208c74283f334e1f047dbbf1daa2407d41d4689aca67c422796f936acce16b7`.

In your smart contract it'll be stored like that:

```
slot m => bar
slot m + 1 => baz.low
slot m + 2 => baz.high
```

So now you can easily understand why this would collide. The list also stores every values next to eachother so If we modify `Foo` to this:
```rs
struct Foo {
    bar: List<felt252>,
    baz: u256
}
```

it'll be like that in your contract when you only have 1 element in bar:
```
slot m => bar[0]
slot m + 1 => baz.low
slot m + 2 => baz.high
```

now we append 1 value to `bar`

```
slot m => bar[0]
slot m + 1 => bar[1]
slot m + 2 => baz.high
```
and so on
