### ISSUE TITLE
feat: add: Solidity-like abi.encode functions

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/alexandria#274]
# Feature Request

It would be helpful to have utilities to emulate the following functionalities that solidity provides : 
- `abi.encode`
- `abi.encodePacked`

There are some other ABI functions, too, which are less valuable in the immediate term:
- `abi.encodeWithSelector`
- `abi.decode`
- `abi.encodeWithSignature`
- ...

These would be super helpful in the [Blobstream Cairo contracts](https://github.com/keep-starknet-strange/blobstream-starknet/tree/main), which are porting the Blobstream solidity contracts.
[Corresponding issue](https://github.com/keep-starknet-strange/blobstream-starknet/issues/69)

**Preferred Solution**

It's a little tricky because Cairo 1 doesn't support variadic arguments. I think the preferred solution would be something like : 
```
trait EthAbiEncodeTrait<T> {
    fn encode(self: Bytes, x: T) -> Bytes;
    fn encodePacked(self: Bytes, x: T) -> Bytes;
}
```
With the trait implemented for each type. Allowing us to use it like this : 
```
let x32: u32 = 100;
let x64: u64 = 200;
let mut bytes: Bytes = BytesTrait::new_empty();
bytes.encodePacked(x64).encodePacked(x32)
```

[More info here](https://github.com/keep-starknet-strange/blobstream-starknet/issues/69).

**Alternatives**

Currently, there exists the alternative of just using the `BytesTrait` in `alexandria` with the `append_X` functions as described in the [README.md](https://github.com/keep-starknet-strange/alexandria/blob/main/src/bytes/README.md). But, this is more error-prone because users need to understand the nuances of the `encode` function.

**Related Code**

[Example here.](https://github.com/keep-starknet-strange/blobstream-starknet/issues/69#issuecomment-1932558985)

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes
- [ ] No

**Comment by drspacemn** [comment]
@LucasLvy thoughts on this addition?

**Comment by LucasLvy** [comment]
sure but add that in a new crate ?

**Comment by b-j-roberts** [comment]
Sure. A couple possible names for the new crate might be `sol_tools`, `sol_utils`, `eth_tools`, `eth_utils`, or maybe someone has a better idea?

I think the existing `encoding` crate could be good too. I could add a module called `abi`, `eth_abi`, or `sol_abi`.

**Comment by LucasLvy** [comment]
Up to you no strong opinion here

**Comment by b-j-roberts** [comment]
I created a PR adding the main desired functionalities. Some notes on other things that might be interesting to add in the future :

- Support for Solidity string formats
- Integer types encoding/decoding, ie i8, i16, ...
- Read a b`ByteArray`( string ) as a hex string and convert to bytes
- Solidity function Signature -> selector computation like :
```            
fn signature_to_selector(signature: Bytes) -> u32 {
   ...
}

fn signature_bytes_array_to_selector(signature: ByteArray) -> u32 {
    ...
}

fn encode_signature(mut self: Bytes, signature: Bytes) -> Bytes {
    self.append_u32(signature_bytes_to_selector(signature));
    self
}

fn encode_signature_byte_array(mut self: Bytes, signature: ByteArray) -> Bytes {
    self.append_u32(signature_to_selector(signature));
    self
}
```
