### ISSUE TITLE
dev: Gas metering

### ISSUE THREAD

**Issue by gaetbout** [keep-starknet-strange/alexandria#292]
Add a GH action that will print a gas report and szhould fail if that gas report isn't up to date
This will allow to compare the effect a PR has over the code base in terms of gas

**Comment by gaetbout** [comment]
Ping

**Comment by gaetbout** [comment]
Pong

**Comment by gaetbout** [comment]
.

**Comment by harsh-ps-2003** [comment]
@gaetbout can you elaborate `gas report isn't up to date`? we will have a latest gas_report, and we will compare the PRs gas report with pre-existing one. If the gas is equal or less consumed, then the PR passes, otherwise, if the gas increases, then the PR should fail. am I right?
