### ISSUE TITLE
bug: BytesTrait keccak computation mismatch

### ISSUE THREAD

**Issue by JordyRo1** [keep-starknet-strange/alexandria#317]
# Bug Report

**Alexandria version:**

This bug appears for the most recent Alexandria version [cairo-v2.6.0](https://github.com/keep-starknet-strange/alexandria/releases/tag/cairo-v2.6.0)

**Current behavior:**
The BytesTrait keccak function sometimes output incorrect hash, notably when 0-padding is involved. Let me explain with an example.
The objective was to compute the keccak hash of the felt252 element:  `0x48595045524c414e455f414e4e4f554e43454d454e54`. The python implementation provided on [tests](https://github.com/keep-starknet-strange/alexandria/blob/main/packages/bytes/src/tests/test_bytes.cairo)
was used to check if the result matches the expectation. The expected result from the python script was `0xda15cbb01a970c130a1bf6ba8b35fcff0fabd4695bfb03f4454482023f2ae84c`. The function keccak from BytesTrait and from the python script have inverse endianness, so the expected result should be `0x4CE82A3F02824445F403FB5B69D4AB0FFFFC358BBAF61B0A130C971AB0CB15DA`. 
However, the output result from the bytes.keccak() is `0x93F59F2604EE54DE51A2DFCFB3E0A6D74EDE53826CF2D1CBA9422A06AF66BC65`. After further investigation, the input argument that could possibly lead to this hash is `0000000000000000000048595045524c414e455f414e4e4f554e43454d454e54`. 
This is why I assume the error might be linked to the padding , unless I am missing something. 

**Expected behavior:**

The output hash of the keccak function should match the one computed using the python script. 

**Steps to reproduce:**

You can just append the following lines to the `test_bytes_keccak` function for example to test. 

**Related code:**

```rust
let mut bytes : Bytes = BytesTrait::new_empty();
bytes.append_felt252(0x48595045524c414e455f414e4e4f554e43454d454e54);
let res = bytes.keccak();
assert_eq!(res, 0x4CE82A3F02824445F403FB5B69D4AB0FFFFC358BBAF61B0A130C971AB0CB15DA);
```
```python
from Crypto.Hash import keccak
k = keccak.new(digest_bits=256)
k.update(bytes.fromhex('48595045524c414e455f414e4e4f554e43454d454e54'))
print(k.hexdigest()) 
# output: da15cbb01a970c130a1bf6ba8b35fcff0fabd4695bfb03f4454482023f2ae84c
```

**Comment by gaetbout** [comment]
Gm gm,
Could only have a very quick look so far so I'll take a look more in depth later when I can.
Are you sure it didn't happen before v2.6.0?
Because the changes done [in that diff](https://github.com/keep-starknet-strange/alexandria/compare/cairo-v2.5.4...cairo-v2.6.0) are only syntactic changes.

**Comment by JordyRo1** [comment]
Hey, no sorry I meant that the version that I used for the test was 2.6.0. But it occurs with previous versions too. Thank you for your time.

**Comment by gaetbout** [comment]
GM @zkcarter 
You are the one that did this file, would you have any idea :) ?

**Comment by gaetbout** [comment]
This code should be removed thanks to:
https://github.com/starkware-libs/cairo/pull/5877 
When they release it

**Comment by gaetbout** [comment]
@JordyRo1 do you still think it needs to be addressed given that it'll be part of the standard library?
Don't close this issue, we'll keep it as a reminder to remove that piece of code :)

**Comment by JordyRo1** [comment]
@gaetbout No it's not necessary anymore, no problem I will not delete it !

**Comment by zkcarter** [comment]
Hi @gaetbout BytesTrait is a supplement to the standard library that has been developed for some time. I believe that once these functions are implemented in the standard library, this code should be removed, and developers should be encouraged to use the standard library.

**Comment by gaetbout** [comment]
We'll do it, thanks @zkcarter !

**Comment by gaetbout** [comment]
Stay alive

**Comment by gaetbout** [comment]
Should be solved with https://github.com/keep-starknet-strange/alexandria/pull/321

**Comment by gaetbout** [comment]
Solved with https://github.com/keep-starknet-strange/alexandria/pull/321

**Comment by gaetbout** [comment]
@JordyRo1 Can you close this :) ?
