### ISSUE TITLE
feat: add pow2 and pow10 utilizing const arrays

### ISSUE THREAD

**Issue by milancermak** [keep-starknet-strange/alexandria#323]
# Feature Request

**Describe the Feature Request**

Cairo 2.7.0 brought back the use of `dw` in const array. In Cairo0, it was used by a lot of projects to have the most efficient implementation of power of 2 and power of 10 since instead of looping it's just a lookup table.

pow2 and pow10 are the most commonly used powers - for example, the former is used in Alexandria as well for bitshifting, the latter is often used for defi applications as we deal with powers of ERC20.decimals there.

**Describe Preferred Solution**

Something like: 

```cairo
pub fn pow10(n: usize) -> u128 {
    *(P10.span()[n])
}
```
And similarly for `pow2`.

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by PavitraAgarwal21** [comment]
can i take this up

**Comment by oluwa-peski** [comment]
Is this issue still open? I'd like to complete it, but can't find a way to apply for it on onlydust

**Comment by milancermak** [comment]
issue still valid

**Comment by Th0rgal** [comment]
Will do, I need it
