### ISSUE TITLE
bug: Doesn't support Cairo 2.8 (A lot of warnings)

### ISSUE THREAD

**Issue by RealJohnnyTime** [keep-starknet-strange/alexandria#330]
# Bug Report

**Alexandria version:**
82088715b454d8cf197b9c54c31525ca0cb57a05

**Current behavior:**
There are plenty of warnings while building the project with the most recent Scarb.

**Expected behavior:**
No warning should be present

**Steps to reproduce:**
Just upgrade Scarb, SNFoundry, and Universal Sierra to the most recent versions and try to build a project which is using Alexandria.

**Related screendhots:**
<img width="1704" alt="Screenshot 2024-09-03 at 12 58 50" src="https://github.com/user-attachments/assets/8c64d3ec-a88e-4386-b91f-3c86284294da">

**Comment by RealJohnnyTime** [comment]
Some more context:
<img width="1353" alt="image" src="https://github.com/user-attachments/assets/eabf3239-eb8f-4487-aa7b-7a13b0b15ef1">

**Comment by maxdesalle** [comment]
Getting something similar on my end, an upgrade to Cairo 2.8.0 would be more than welcome 🙏
