### ISSUE TITLE
feat: Red–black tree

### ISSUE THREAD

**Issue by tarrencev** [keep-starknet-strange/alexandria#70]
# Feature Request

**Describe the Feature Request**

A [Red-black tree](https://en.wikipedia.org/wiki/Red%E2%80%93black_tree) is a balanced binary search tree where each node has an additional attribute: color. The color is either red or black, and the tree maintains its balance by following some specific rules. Red-black trees are useful for fast storage and retrieval of ordered information.

**Related Code**

Here's a basic outline of how you could define a Red-Black tree struct and trait in Cairo:
 
```rust
// Enum to represent the color of a node in the Red-Black tree.
enum Color {
    Red,
    Black,
}

// The RedBlackTreeNode struct represents a single node in the Red-Black tree.
struct RedBlackTreeNode<T> {
    color: Color,
    value: T,
    left: Option<RedBlackTreeNode<T>>,
    right: Option<RedBlackTreeNode<T>>,
    parent: Option<RedBlackTreeNode<T>>,
}

// The RedBlackTree struct represents the whole Red-Black tree.
struct RedBlackTree<T> {
    root: Option<RedBlackTreeNode<T>>,
}

trait RedBlackTreeTrait<T> {
    // Creates a new Red-Black tree.
    fn new() -> RedBlackTree;

    // Inserts a value into the Red-Black tree.
    fn insert(ref self: RedBlackTree, value: T);

    // Removes a value from the Red-Black tree.
    fn remove(ref self: RedBlackTree, value: T) -> bool;

    // Searches for a value in the Red-Black tree.
    fn search(self: @RedBlackTree, value: T) -> bool;

    // Returns the minimum value in the Red-Black tree.
    fn min(self: @RedBlackTree) -> Option<T>;

    // Returns the maximum value in the Red-Black tree.
    fn max(self: @RedBlackTree) -> Option<T>;

    // Returns the number of nodes in the Red-Black tree.
    fn len(self: @RedBlackTree) -> usize;
}
```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by neotheprogramist** [comment]
I can take that

**Comment by tarrencev** [comment]
awesome @neotheprogramist! this might be a useful resource: https://github.com/topology-gg/bto-cairo-1

**Comment by neotheprogramist** [comment]
compiler needs to be fixed to allow recursive structs

**Comment by SupremeSingh** [comment]
Throwing in this lead over here too - https://github.com/TheAlgorithms/Rust/blob/master/src/data_structures/rb_tree.rs
