### ISSUE TITLE
feat: Add binary search algorithm

### ISSUE THREAD

**Issue by edisontim** [keep-starknet-strange/alexandria#87]
# Feature Request

**Describe the Feature Request**

Implement a binary search algorithm for sorted arrays

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes

**Comment by neotheprogramist** [comment]
I can handle that, do we need a few versions of bin search, like find first greater or equal, find first greater than, etc?

**Comment by edisontim** [comment]
> I can handle that, do we need a few versions of bin search, like find first greater or equal, find first greater than, etc?

I've already created a PR for this: see https://github.com/keep-starknet-strange/quaireaux/pull/88
