### ISSUE TITLE
fast_power fails for `2**127`

### ISSUE THREAD

**Issue by moodysalem** [keep-starknet-strange/alexandria#95]
https://github.com/keep-starknet-strange/alexandria/blob/922ea0d124ddb48f796cce1419dd56b8ba87740c/quaireaux/math/src/fast_power.cairo#L11-L29

This is because the final base*base multiplication overflows

Can use u256_mul_overflow

**Comment by edisontim** [comment]
Are you working on this? If not I wouldn't mind having a look :)

**Comment by moodysalem** [comment]
I'm not, just found a way to not use pow

**Comment by lambda-0x** [comment]
@moodysalem this should be fixed now, can you confirm and close the issue?

**Comment by LucasLvy** [comment]
Fixed by #104
